server:
  port: 18080
  servlet:
        contextPath: /mk
logging:
  level:
    com.thaisoftplus: DEBUG
spring:
  h2:
    console:
      enable: true
      path: /h2-console
  datasource:
    platform: h2
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    url: jdbc:h2:file:~/mkdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE;MODE=MYSQL;DATABASE_TO_LOWER=TRUE
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update
